# 🧮 NumPy-Einführung für den Kurs *Numerik 1*
Dieses Notebook richtet sich an Studierende, die bereits Python-Erfahrung besitzen. Es dient als Vorbereitung für das Praktikum zur Veranstaltung *Numerik 1* im Bachelor *Angewandte Mathematik und Informatik*.

Weitere Informationen zu NumPy findet man in der API unter [https://numpy.org/doc/stable/reference/](https://numpy.org/doc/stable/reference/)

Insbesondere:
- [Array objects](https://numpy.org/doc/stable/reference/arrays.html)
- [Mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html)
- [Linear Algebra](https://numpy.org/doc/stable/reference/routines.linalg.html)

## Inhalt
1. [Warum NumPy?](#1-warum-numpy)
2. [Arrays erstellen](#2-arrays-erstellen)
3. [Indexing und Slicing](#3-indexing-und-slicing)
4. [Vektorisiertes Rechnen](#4-vektorisiertes-rechnen)
5. [Mathematische Grundfunktionen](#5-mathematische-grundfunktionen)
6. [Lineare Algebra](#6-lineare-algebra)
7. [Numerische Funktionen](#7-numerische-funktionen)
8. [Fallstricke & Tipps](#8-fallstricke--tipps)
9. [Weiterführendes](#9-weitere-nützliche-bibliotheken-für-die-numerik)

## 1. Warum NumPy?
Python-Listen `list` sind flexibel – aber langsam und speicherintensiv, besonders bei numerischen Berechnungen. NumPy bietet:
- Homogene Arrays (alle Elemente gleich typisiert)
- Vektorisierung (schnellere Berechnungen ohne Schleifen)
- Zugriff auf schnelle C-Bibliotheken

In [ ]:
import numpy as np

In [ ]:
liste = list(range(1_000_000)) # Schreibweise mit Unterstrich ab Python 3.6
array = np.arange(1_000_000)

In [ ]:
# Standard-Python
%timeit -n 10 -r 7 [x ** 2 for x in liste] 

In [ ]:
# Numpy
%timeit -n 10 -r 7 array ** 2 

## 2. Arrays erstellen

In [8]:
# Einfache Arrays
a = np.array([1, 2, 3])
b = np.zeros(5)
c = np.ones((2, 3))
d = np.arange(0, 10, 2)
e = np.linspace(0, 1, 5)
a, b, c, d, e

(array([1, 2, 3]),
 array([0., 0., 0., 0., 0.]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [ ]:
# Datentypen prüfen
print(f"Typ von a: {a.dtype}")
print(f"Typ von b: {b.dtype}")

## 3. Indexing und Slicing

In [9]:
import numpy as np
A = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34]
])

print(f"A:\n{A}\n")
print(f"Erstes Element: {A[0,0]}\n")
print(f"Zweite Zeile: {A[1]}\n")
print(f"Zweite Spalte: {A[:,1]}\n")
print(f"Teil-Matrix:\n{A[1:,2:-1]}\n")
print(f"Teil-Matrix:\n{A[1:3,1:4]}")

A:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

Erstes Element: 11

Zweite Zeile: [21 22 23 24]

Zweite Spalte: [12 22 32]

Teil-Matrix:
[[23]
 [33]]

Teil-Matrix:
[[22 23 24]
 [32 33 34]]


In [ ]:
a = np.array([1,4,3,7,2,9])
print(f"{a=}")
perm = a[[2,4,0,3,5,1]]
print(f"{perm=}")



In [ ]:
maske = np.array([True, True, False, True])
a = np.array([1,2,3,4])
# maske = (a % 2 == 0)

print(f"{a[maske]=}")

In [ ]:
print(f"{A=}")
print(f"{A[0,maske]=}")

In [ ]:
indices = np.where(A % 2 == 0)
print(indices)
print(f"{A[indices]}")

## 4. Vektorisiertes Rechnen

In [ ]:
# Ineffizient

import math

xx = []
yy = []
n = 1_000_000
for i in range(0,n):
    x = i*(2*np.pi/n)
    y = math.sin(x) * math.exp(-x)

    xx += [x]
    yy += [y]
    
import matplotlib.pyplot as plt # normalerweise oben importieren
plt.plot(xx, yy)
plt.title(r'$f(x) = \sin(x)\cdot \exp(-x)$')
plt.grid(True)
plt.show()

In [ ]:
# Professioneller

x = np.linspace(0, 2*np.pi, int(1e6))
y = np.sin(x) * np.exp(-x)

import matplotlib.pyplot as plt  # normalerweise oben importieren
plt.plot(x, y)
plt.title(r'$f(x) = \sin(x)\cdot \exp(-x)$')
plt.grid(True)
plt.show()

## 5. Mathematische Grundfunktionen

In [ ]:
mu = 10
sigma = 2
xx = mu + sigma*np.random.randn(3) # Normalverteilte Zufallszahlen
print(f"{xx=}\n")
print(f"{np.abs(xx)=}\n")
print(f"{np.sqrt(xx)=}\n")
print(f"{np.power(xx,2)=}\n")
print(f"{np.exp(xx)=}\n")
print(f"{np.log(xx)=}\n")
print(f"{np.log10(xx)=}\n")
print(f"{np.log2(xx)=}\n")

In [ ]:
print(f"{np.sin(xx)=}\n")
print(f"{np.cos(xx)=}\n")
print(f"{np.tan(xx)=}\n")
print(f"{np.arcsin(np.sin(xx))=}\n")
print(f"{np.arccos(np.cos(xx))=}\n")
print(f"{np.arctan(np.tan(xx))=}\n")

In [ ]:
print(f"{np.mean(xx)=}\n")
print(f"{np.max(xx)=}\n")
print(f"{np.min(xx)=}\n")
print(f"{np.median(xx)=}\n")
print(f"{np.std(xx)=}\n")
print(f"{np.var(xx)=}\n")
print(f"{np.percentile(xx, 0.25)=}\n")

In [ ]:
A = np.array([
    [1, 1, 1],
    [2, 2, 2]
])
print(f"{np.sum(A, axis=0)=}")

## 6. Lineare Algebra

### Grundrechenoperationen

In [ ]:
A = np.array([[1,2,1],
              [3,4,9]]) # 2x3
B = np.array([[4,1,2],
              [7,1,5]]) # 2x3

v = np.array([3,3,3])

## Addition
print(f"Addition: \nA+B = \n{A+B}\n")

## Subtraktion
print(f"Subtraktion: \nA-B = \n{A-B}\n")

## Elementweise Multiplikation
print(f"Elementweise Multiplikation:\nA*B = \n{A*B}\n")

## Elementweise Division
print(f"Elementweise Division:\nA/B = \n{A/B}\n")


In [ ]:
## Matrix-Multiplikation
print("Matrix-Multiplikation:")

# print(f"np.dot(A,B.T) = \n{np.dot(A,B.T)}\n") # veraltet, aber möglich
# print(f"A.dot(B.T) = \n{A.dot(B.T)}\n") # veraltet, aber möglich

# Modern:
print(f"A @ B.T = \n{A @ B.T}\n") # B.T = B.transpose()
print(f"np.matmul(A,B.T)= \n{np.matmul(A,B.T)}\n") # A @ B = np.matmul(A,B)

## Matrix-Vektor-Multiplikation
print("Matrix-Vektor-Multiplikation:")
print(f"A @ v = \n{A @ v}\n")
print(f"A @ v.T = \n{A @ v.T}\n")
print(f"v @ A.T = \n{v @ A.T}\n")
print(f"v.T @ A.T = \n{v.T @ A.T}\n")

In [ ]:
A = np.array([
    [1,2,3],
    [1,2,3]
])
B = np.array([
    [4,4,4]
])
C = np.array([
    [5],
    [5],
    [5]
])
x = np.array([5,5,5])

print(f"{A.shape=}")
print(f"{B.shape=}")
print(f"{C.shape=}")
print(f"{x.shape=}")

### Broadcasting

Wenn zwei Arrays, mit womöglich unterschiedlichen Dimensionen, verknüpft werden sollen (z.B. durch `+`,`-`,`*`,`/`,`@`), läuft das wie folgt ab:

> (1) **Einseitige Erweiterung**: 

>> - Das Array mit weniger Dimensionen wird **von links** mit `1`-en ergänzt.

> (2) **Kompatiblität der Dimensionen**: Zwei Dimensionen sind **kompatibel**, wenn

>> - sie **gleich** sind, oder

>> - eine von **beiden** `1` ist $\Rightarrow$ Kleinere Dimesion wird *gestreckt* (broadcasted), ohne dass neue Daten allokiert werden.

> (3) **Fehler bei Imkompatibilität**: 

>> - Wenn **keine** der beiden Bedingungen in (2) erfüllt ist, wird ein `ValueError: operands could not be broadcast together with shapes` geworfen

In [ ]:
print(f"{A + B=}")
"""
B wird als Zeilenvektor bzw. 1x3 Matrix kopiert, sodass er zu einer 2x3 Matrix wird
""";

In [ ]:
# print(f"{A + C=}")
"""
Nicht möglich, da von den Dimensionen (2,3) und (3,1) nur 3 und 1 kompatibel sind, 
aber 2 und 3 führen zum ValueError 
""";

In [ ]:
print(f"{A + x=}")
"""
Shape von x wird von links mit 1 aufgefüllt zu (1,3). 
Anschließend wird es auf (2,3) erweitert, indem der Zeilenvektor kopiert wird.
""";

In [ ]:
print(f"{B+C=}")
"""
B hat shape (1,3) und C (3,1). Somit sind jeweils beide Dimensionen kompatibel. 
Der Zeilenvektor B wird kopiert zu (3,3). Der Spaltenvektor C wird ebenfalls 
kopiert zu (3,3).
""";

In [ ]:
A = np.random.rand(5,3,3)
print(f"{A.shape=}\n")

x = np.ones(3)
print(f"{x.shape=}")

In [ ]:
print(f"{A + x=}")
"""
Shape von x wird von links mit 1 aufgefüllt zu (1,1,3). Anschließend wird x analog zu oben auf (5,3,3) aufgefüllt. x sieht dann für den Moment so aus:
""";
# print(f"x* = {(A + x) - A=}")

### Hilfreiche Funktionen

### `numpy.shape` und `numpy.reshape`
`numpy.shape` dient als Äquivalent einer ***getter***-Funktion und `numpy.reshape` als ***setter***-Funktion

In [ ]:
A = np.array([[1,2,1],
              [3,4,9]]) # 2x3
B = np.array([[4,1,2],
              [7,1,5]]) # 2x3

v = np.array([3,3,3])

print(f"{A.shape=}")
print(f"{v.shape=}")
print(f"{(A@v).shape=}")
print(f"{(A@v.T).shape=}")
print(f"{(v@A.T).shape=}")
print(f"{(v.T@A.T).shape=}")

In [ ]:
v_row = v.reshape(1, -1)
v_col = v.reshape(-1, 1)
"""
'-1' gilt als Anweisung zum automatischen Auffüllen der entsprechenden Dimension
""";
print(f"{v_row.shape=}")
print(f"{v_col.shape=}")

a = A.reshape(-1)
"""
macht aus Matrix A mit shape (n x m) einen Vektor mit n*m Elementen
"""

In [ ]:
# w = np.array([[2],[2],[2]]) # w.shape = (3,1)
w = np.array([[2,2,2]])     # w.shape = (1,3)
print(f"{w=}")
print(f"{w.shape=}")
# print(f"{(A@w).shape=}")
print(f"{(A@w.T).shape=}")
print(f"{(w@A.T).shape=}")
# print(f"{(w.T@A.T).shape=}")

In [ ]:
v = np.array([1,2,3])
w = np.array([4,5,6])
print(f"v@w = \n{v@w=}")

### `numpy.outer`
Dient zum Berechnen des **äußeren Produktes** zweier Vektoren

In [ ]:
print(f"np.outer(v,w) = \n{np.outer(v,w)}")

In [ ]:
v = np.array([[1],[2],[3]]) # 3x1 Matrix
w = np.array([[4],[5],[6]]) # 3x1 Matrix
print(f"v.T@w = \n{v.T@w}\n") # Skalarprodukt
print(f"v@w.T = \n{v@w.T}")   # äußeres Produkt

### `numpy.linalg.solve`
Ist aus dem Modul [numpy.linalg](https://numpy.org/doc/stable/reference/routines.linalg.html) und dient zum Berechnen von linearen Gleichungssystemen $Ax=b$

In [ ]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
x

In [ ]:
print(f"{A@x-b=}")

### `numpy.linalg.norm`
Berechnet die Norm von Matrizen und Vektoren. Standard für
- Vektoren: 2-norm, also die euklidische Norm $\|v\|_2 = \left[\sum_{i}v_{i}^2\right]^{\frac{1}{2}}$
- Matrizen: Frobeniusnorm 'fro' $\|A\|_F = \left[\sum_{i,j}|a_{i,j}|^2\right]^{\frac{1}{2}}$

In [ ]:
v = A@x-b
print(f"{v=}\n")
print(f"{np.linalg.norm(v)=}\n") # Euklidische Norm
print(f"{np.linalg.norm(v,1)=}\n") # Betragsnorm = np.sum(np.abs(v))
print(f"{np.linalg.norm(v,np.inf)=}\n") # Maximumsnorm = np.max(np.abs(v))

In [ ]:
print(f"{A=}\n")
print(f"{np.linalg.norm(A)=}\n") # Frobeniusnorm
print(f"{np.linalg.norm(A,1)=}\n") # Spaltensummennorm = np.max(np.sum(np.abs(A), axis=0))
print(f"{np.linalg.norm(A,np.inf)=}\n") # = Zeilensummennormn = np.max(np.sum(np.abs(A), axis=1))

### numpy.linalg.inv
Berechnet die Inverse einer quadratischen regulären Matrix. **VORSICHT** bei schlecht konditionierten Matrizen.

**Hinweis**: Sollte vermieden werden, wo es geht. Stattdessen ist es oftmals besser, Gleichungen/Formeln so umzustellen, dass man *nur* ein lineares Gleichungssystem zu berechnen hat. Statt beispielsweise $x = (A^TA)^{-1}A^Tb$ besser $Cx=y$ lösen mit $C=A^T A$ und $y=A^T b$

In [ ]:
# Hilbert-Matrix für n = 5
H = np.array([
    [1.   , 1/2  , 1/3  , 1/4  , 1/5  ],
    [1/2  , 1/3  , 1/4  , 1/5  , 1/6  ],
    [1/3  , 1/4  , 1/5  , 1/6  , 1/7  ],
    [1/4  , 1/5  , 1/6  , 1/7  , 1/8  ],
    [1/5  , 1/6  , 1/7  , 1/8  , 1/9  ]
])

print(f"{np.linalg.inv(H)@H}")

### numpy.linalg.det
Berechnet die Determinante einer quadratischen Matrix

In [ ]:
A = np.array([[2,3],[1,-1]])
print(f"{np.linalg.det(A)=}")

## 7. Numerische Funktionen

### numpy.gradient
Bestimmt die Ableitung mittels Zentraler Differenzen.

In [ ]:
x = np.linspace(0, 10, 100)
y = np.sin(x)* np.exp(-x)
dy_dx = np.gradient(y, x)
plt.plot(x, y, label='$\sin(x)\cdot \exp(-x)$')
plt.plot(x, dy_dx, label='Ableitung')
plt.legend()
plt.grid(True)
plt.show()

### numpy.trapezoid

Bestimmt das Integral mittels summierter Trapezregel

In [ ]:
x = np.linspace(0, 2*np.pi, 1000)
y = np.sin(x) * np.exp(-x)

area = np.trapezoid(y,x)
plt.plot(x, y)
plt.fill_between(x, y, alpha=0.3)
plt.title(rf"Trapezintegral $\approx$ {area:.5f}")
plt.grid(True)
plt.show()



## 8. Fallstricke & Tipps

In [ ]:
a = np.array([1, 2, 3])
b = a  # keine Kopie!
b[0] = 99
print(f"{a=}")  # Auch a ist verändert!

# Richtige Kopie:
c = a.copy()
c[0] = 1
print(f"{a=} , {c=}")

In [ ]:
a = np.array([0,1,2,3,4,5,6])
print(f"{a[2:5]=}")

In [ ]:
# Erinnerung an oben
v = np.array([1,2,3,4])
print(f"{v.shape}")
print(f"{v.reshape(1,-1).shape}")
print(f"{v.reshape(-1,1).shape}")

In [ ]:
# Zudem noch...
w = v.reshape(2,2) # keine Kopie!
w[0,0] = 17
print(f"{v=}")

In [ ]:
# Vergleich von 'floats'
a = 0.1 + 0.2
b = 0.3
print(a==b)

In [ ]:
# besser...
print(np.abs(a-b) < np.finfo(np.float64).eps)

# oder
print(np.isclose(a, b))

## 9. Weitere nützliche Bibliotheken für die Numerik

- [scipy](https://docs.scipy.org/doc/scipy/reference/): Erweiterte numerische Verfahren
- [sympy](https://docs.sympy.org/latest/reference/index.html): Symbolisches Rechnen für exakte Ableitungen, Vereinfachungen, analytische Lösungen (aber auch langsamer)
- [numba](https://numba.pydata.org/numba-doc/dev/index.html): massive Speedups für Schleifen und Algorithmen durch Just-in-Time-Kompilierung